# Generated by Django 5.1.2 on 2024-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, verbose_name='Plate Number')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254, verbose_name='User Email')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Phone Number')),
            ],
        ),
    ]
