# Generated by Django 5.1.2 on 2024-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
