# Generated by Django 5.1.2 on 2024-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_drivers_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
